altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  509e5f32-08b6-48fe-84c5-e947c8959e5c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-17T21:57:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 26316d01-dae5-4680-bbcb-a14a9ae157c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20eb688c-da23-4373-b6ac-7908764ca1aa
        userCondition: null
fs: localFiles
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localFiles
transformSubpath: ''
